AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  
Globals:
  Function:
    Timeout: 600

Resources:
  ExpressApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      BinaryMediaTypes: ['*/*']
      Domain:
        DomainName: {put-domain-name-here}
        CertificateArn: {put-acm-arm-here}
        Route53:
          HostedZoneId: {put-hosted-zon-id-here}
      
  ExpressFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: api/
      Handler: lambda.handler
      Runtime: nodejs14.x
      MemorySize: 512
      Events:
        ExpressFunction:
          Type: Api
          Properties:
            RestApiId: !Ref ExpressApi
            Path: "/{proxy+}"
            Method: ANY
            
      Policies:
      # Give DynamoDB Full Access to your Lambda Function
      - AmazonDynamoDBFullAccess
  
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName : Movies
      AttributeDefinitions: 
        - AttributeName: year
          AttributeType: N
        - AttributeName: title
          AttributeType: S

      KeySchema: 
        - AttributeName: year
          KeyType: HASH
        - AttributeName: title
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

Outputs:

  ExpressFunctiondApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ExpressApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  ExpressFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt ExpressFunction.Arn
  ExpressFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt ExpressFunctionRole.Arn